### PR TITLE
Project set-up for ftp plugin

### PR DESCRIPTION
**Pull request by flakrimjusufi**
FTP Test cases: 
https://docs.google.com/spreadsheets/d/1JiHWejJsEWl4hPcBl5bprVCc-8pBd2FCE55fwQ42D_4/edit?usp=sharing

SFTP Test cases: 
https://docs.google.com/spreadsheets/d/1A92y2uf4nl7TKgqj6gJNYcSBhEKKFCGnlQBWby3wPwo/edit?usp=sharing

All test cases that were done manually are passing successfully. 

There's just one minor issue that is happening only in **CDAP 6.4.0.** 

`FileSystemProperties` throws a null exception **after** you delete the properties {} and leave the FileSystemProperties empty. 

This happens only if you type the properties first and then remove them all leaving fileSystemProperties empty. 
This action, in prepare run will send an empty string **""** instead of **null** and as result this will fail with null exception.
Error message: `Null error occurred while configuring the stage FTP.`

It seems more like an UI issue but this can also be handled from our side by changing this condition: 

https://github.com/AdaptiveScale/ftp-plugins/blob/cae17ff8d6128e777917c7750614331f17220d9b/src/main/java/io/cdap/plugin/batch/source/FTPBatchSource.java#L255-L257

to: 

`if (!Strings.isNullOrEmpty(fileSystemProperties) `

NOTE: The change should also be applied in core-plugins.

### CODE REVIEW

**Review by rmstar — APPROVED** [review]

**Review by rmstar — APPROVED** [review]
Thanks!
Please open hub PR

**Comment by rmstar** [comment]
Also, can you please open a separate PR for the `Null error occurred while configuring the stage FTP.` issue.

**Comment by rmstar** [comment]
> Also, can you please open a separate PR for the `Null error occurred while configuring the stage FTP.` issue.

Please ignore this comment - I have fixed this in #2

**Comment by flakrimjusufi** [comment]
> > Also, can you please open a separate PR for the `Null error occurred while configuring the stage FTP.` issue.
> 
> Please ignore this comment - I have fixed this in #2

Shall we do the same thing in `core-plugins`?

**Comment by rmstar** [comment]
@flakrimjusufi I also fixed core-plugins in https://github.com/cdapio/hydrator-plugins/pull/1332.

**Pull request merged**
